# Generated by Django 5.2.3 on 2025-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='REG_no',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
