# Generated by Django 5.2.3 on 2025-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_useraccount_phone_number_useraccount_reg_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='batch',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='depertment',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
