# Generated by Django 5.2.3 on 2025-07-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useraccount_batch_useraccount_depertment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='depertment',
            new_name='department',
        ),
    ]
