# Generated by Django 5.2.3 on 2025-07-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_useraccount_batch_alter_useraccount_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='department',
        ),
    ]
