# Generated by Django 5.2.3 on 2025-07-02 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_useraccount_batch_and_more'),
        ('home', '0002_routeen'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.batch'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department'),
        ),
    ]
