# Generated by Django 5.2.3 on 2025-07-02 20:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_useraccount_batch_useraccount_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='REG_no',
            field=models.CharField(default=core.models.generate_custom_id, unique=True),
        ),
    ]
