# Generated by Django 5.2.3 on 2025-07-02 20:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_useraccount_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='REG_no',
            field=models.CharField(default=core.models.generate_custom_id, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=500, unique=True),
        ),
    ]
