# Generated by Django 5.2.3 on 2025-07-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_useraccount_reg_no_alter_useraccount_email'),
        ('home', '0005_routeen_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.university'),
            preserve_default=False,
        ),
    ]
