# Generated by Django 5.2.3 on 2025-07-17 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_useraccount_university'),
        ('home', '0005_routeen_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.batch', verbose_name='Batch or Session'),
        ),
    ]
