# Generated by Django 5.2.3 on 2025-07-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_useraccount_batch'),
        ('home', '0006_remove_batch_university_department_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.university'),
        ),
    ]
