# Generated by Django 5.2.3 on 2025-07-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_useraccount_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_CR',
            field=models.BooleanField(default=False),
        ),
    ]
