# Generated by Django 5.2.3 on 2025-07-17 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_remove_batch_university_department_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'saturday')], default='sunday', max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=500)),
                ('shift_no', models.PositiveIntegerField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.university')),
            ],
            options={
                'ordering': ['university', 'shift_no'],
                'unique_together': {('university', 'shift_no')},
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=500, verbose_name='Course Name')),
                ('room', models.CharField(max_length=500, verbose_name='Romm no.')),
                ('faculty', models.CharField(max_length=500, verbose_name='Faculty details')),
                ('shedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_routine.shedule')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_routine.shift')),
            ],
        ),
    ]
