# Generated by Django 5.2.3 on 2025-07-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_routine', '0002_alter_shift_shift_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
