# Generated by Django 5.2.3 on 2025-07-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_routine', '0003_alter_shift_shift_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shift',
            name='university',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
