# Generated by Django 5.2.3 on 2025-07-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_routine', '0005_shift_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='shedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shedule', to='my_routine.shedule'),
        ),
    ]
