# Generated by Django 5.2.3 on 2025-07-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_routeen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='depertment',
        ),
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='home.department'),
            preserve_default=False,
        ),
    ]
