# Generated by Django 5.2.3 on 2025-07-17 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_university_alter_batch_options_batch_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeen',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.university'),
            preserve_default=False,
        ),
    ]
