# Generated by Django 5.2.3 on 2025-07-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_routeen_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='university',
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.university'),
            preserve_default=False,
        ),
    ]
