# Generated by Django 5.2.3 on 2025-07-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_batch_university_department_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='home.department'),
        ),
    ]
