# Generated by Django 5.2.3 on 2025-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_batch_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='universityImage'),
        ),
    ]
