# Generated by Django 5.2.3 on 2025-07-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_routeen_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
